#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /index
  controller : App\Controller\MainController::index

maintenance:
  path: /
  controller: App\Controller\MainController::maintenance

