#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: App\Controller\MainController::maintenance

homepage:
  path: /index
  controller: App\Controller\MainController::index